### ISSUE TITLE
new ZkUtils() 不work

### ISSUE THREAD

**Issue by sophiazy** [PinkHello/GoPush#4]
DataCenterDiscoveryService 这个类中的  zkUtils = new ZkUtils(); 这行代码运行不了， 报错是Caused by: java.lang.IllegalArgumentException: null
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314) ~[na:1.8.0_192]

启动NodeServerApplication就会报上面的错误，不知道你那边可以运行吗？需要怎么改？

**Comment by PinkHello** [comment]
你自己要看一下了

**Comment by pinkhello** [comment]
问题详细一下
